### ISSUE TITLE
Custom variant profile: Bad line

### ISSUE THREAD

**Issue by LauraVP1994** [fmfi-compbio/virpool#1]
Dear,

I tried running the tool for a new variant profile with GISAID data, and I get this error

`bad line Virus name     Last vaccinated Passage details/history Type    Accession ID Collection date  Location        Additional location information Sequence length Host Patient age      Gender  Clade   Pango lineage   Pango version   Variant AA Substitutions      Submission date Is reference?   Is complete?    Is high coverage?       Is low coverage?      N-Content       GC-Content (expected 22 columns) at ./src/gisaid/process_gisaid.pl line 119, <$in> line 1.
`

with this command
`
./src/gisaid/process_gisaid.pl metadata_tsv_2023_03_06.tar.xz sequences_fasta_2023_03_06.tar.xz 2023_03_06_metadata_sample.tsv 2023_03_06_gisaid_sample.fasta.gz
`

Is it possible that the GISAID metadata has changed since last year?

**Comment by japdlsd** [comment]
Hi, @LauraVP1994 :) 

You are right, the format has been changed.

This is the part of the original script which parses the GISAID data (https://github.com/fmfi-compbio/virpool/blob/88d5e44d887a657d261f839a4679393d2d617685/src/gisaid/process_gisaid.pl#L114): 

```perl
 while(my $line = <$in>) {
	$line_num++;
	chomp $line;  # rmeove end of line
	my @parts = split "\t", $line;  # split to columns
	next if @parts==0;  # skip empty lines
	die "bad line $line (expected 22 columns)" unless @parts == 22;  # check that we have 22 columns
	my ($name, $date, $ncount, $seq_len) = @parts[0, 3, 20, 6];  # store needed columns to variables
	
	if($line_num == 1) {    
	    # check header line, if selected columns have the correct names
	    die "bad header line $line" unless
		$name eq "Virus name"
		and $date eq "Collection date"
		and $ncount eq "N-Content"
		and $seq_len eq "Sequence length";

	    if($phase == 2) {  # print header in phase 2
		print $out $line, "\n";
	    }
	    next;  # go to the next line
	} 
```

The newer version could be something like this:

```perl
while(my $line = <$in>) {
        $line_num++;
        chomp $line;  # rmeove end of line
        my @parts = split "\t", $line;  # split to columns
        next if @parts==0;  # skip empty lines
        
        next if @parts < 24;
        die "bad line $line (expected 24 columns)" unless @parts == 24;  # check that we have 22 columns
        
        my ($name, $date, $ncount, $seq_len) = @parts[0, 5, 22, 8];  # store needed columns to variables
        
        if($line_num == 1) {    
            # check header line, if selected columns have the correct names
            
            my $separated_line = $line;
            $separated_line =~ s/\t/|/g;
            print $separated_line;
            
            die "bad header line $line" unless
                $name eq "Virus name"
                and $date eq "Collection date"
                and $ncount eq "N-Content"
                and $seq_len eq "Sequence length";

            if($phase == 2) {  # print header in phase 2
                print $out $line, "\n";
            }
            next;  # go to the next line
        } 

```

I will update the script in the repo :)

**Comment by japdlsd** [comment]
The file has been updated, I hope it works for you now :)

**Comment by LauraVP1994** [comment]
Dear,

I have just tried the new script and still get this error:

`bad line Virus name     Last vaccinated Passage details/history Type    Accession ID Collection date  Location        Additional location information Sequence length Host Patient age      Gender  Clade   Pango lineage   Pango version   Variant AA Substitutions      Submission date Is reference?   Is complete?    Is high coverage?       Is low coverage?      N-Content       GC-Content (expected 22 columns) at ./src/gisaid/process_gisaid_old_format.pl line 119, <$in> line 1.
`

**Comment by LauraVP1994** [comment]
Thank you for getting back so quickly. It seems to be working, but the rights needed to be changed at first.

**Comment by japdlsd** [comment]
You are welcome 🙂 you are right again, I'll update the rights soon
